# Measuring Distance

 
### Cosine Similarity, Eucledian Distance , Transformers

In [1]:
import pandas as pd
import numpy as np
import re,string
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')

from sklearn.feature_extraction.text import TfidfVectorizer 
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.metrics.pairwise import euclidean_distances

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


In [2]:
d1 = "Machine learning and AI are interrelated"
d2 = "AI is a subset of machine learning"
d3 = "He rose to fame at age twelve, when he began portraying Harry Potter in the film series of the same name "
d4 = "Harry Potter is a series of seven fantasy novels written by British author J. K. Rowling. "
d5 = "Machine learning algorithms use historical data as input to predict new output values."
documents = [d1, d2, d3, d4,d5]



In [3]:
documents_df=pd.DataFrame(documents,columns=['documents'])

stop_words_l=stopwords.words('english')
documents_df['documents_cleaned']=documents_df.documents.apply(lambda x: " ".join(re.sub(r'[^a-zA-Z]',' ',w).lower() for w in x.split() if re.sub(r'[^a-zA-Z]',' ',w).lower() not in stop_words_l) )

tfidfvectoriser=TfidfVectorizer()
tfidfvectoriser.fit(documents_df.documents_cleaned)
tfidf_vectors=tfidfvectoriser.transform(documents_df.documents_cleaned)

pairwise_similarities=np.dot(tfidf_vectors,tfidf_vectors.T).toarray()


print(pairwise_similarities[0])

print(pairwise_similarities[3])




[1.         0.60752662 0.         0.         0.17863166]
[0.         0.         0.20686955 1.         0.        ]


In [7]:


vectorizer = CountVectorizer()
features = vectorizer.fit_transform(documents_df['documents_cleaned']).todense()

for f in features:
    print( euclidean_distances(features[0], f) )

[[0.]]
[[1.41421356]]
[[3.87298335]]
[[3.74165739]]
[[3.31662479]]


/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:598: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:598: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/utils/validation.py:598: FutureWarning: np.matrix usage is deprecated in 1.0 and will raise a TypeError in 1.2. Please convert to a numpy array with np.asarray. For more information see: https://numpy.org/doc/stable/reference/generated/numpy.matrix.html
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn

In [8]:
# Mathematical representation of eucledian distance

def eucledian_dist(a,b):
  return np.sqrt(np.sum(np.square(a - b)))

In [9]:
eucledian_dist(features[0], features[2])

3.872983346207417

In [ ]:
vectorizer = CountVectorizer()
features = vectorizer.fit_transform(documents_df['documents_cleaned']).todense()

for f in features:
    print(cosine_similarity(features[0], f))

In [11]:
# Mathematical representation of cosine similarity

def cosine_sim(a, b): 
	return np.dot(a, b.T) / (np.linalg.norm(a) * np.linalg.norm(b))

In [12]:
cosine_sim(features[0], features[1])

matrix([[0.75]])

In [ ]:
!pip install sentence_transformers

from sentence_transformers import SentenceTransformer

model= SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

In [19]:
embeddings= model.encode(documents)

embeddings.shape

(5, 384)

In [20]:
from sentence_transformers.util import cos_sim

scores = cos_sim(embeddings[0], embeddings[1:])


from sklearn.metrics.pairwise import cosine_similarity
scores= cosine_similarity(
    [embeddings[0]],
    embeddings[1:]
)

In [16]:
scores

array([[ 0.7302327 , -0.02739054,  0.06554236,  0.52872294]],
      dtype=float32)

In [17]:
# documents[scores.argmax().item()+1]